### ISSUE TITLE
requirements.txt'de github linki

### ISSUE THREAD

**Issue by Cediddi** [yogurt-cultures/laktoz#2]
Selam,
`git+https://github.com/yogurt-cultures/kefir.git`
bu satıra gerek yok, kefir zaten pypi'de var :)

**Comment by fatiherikli** [comment]
direkt master'ı laktoz üzerine kullanabilmek için o git url'ini koydum. her seferinde pypi üzerinde release çıkmamak için

**Comment by fatiherikli** [comment]
"laktoz kefir projesinin staging ortamıdır" diyebiliriz

**Comment by Cediddi** [comment]
kefir'in master'ı stable olacaksa zaten sorun yok. yüzlerce laktoz instance'ı kurarsa bi firma, o zaman pypi'ye çeviririz :P
